apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-urtd
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/redhat-appstudio/user-workload@sha256:6276ce968664114878adf6157405a858d7d191f44642d6335d3679baa8c5116c
        name: container-image
        resources: {}
status: {}
